mcauser/awesome-micropython

readme.md
I have removed a duplicate entry under the IDE section of this document.
- JetBrains MicroPython Plugin - Support for MicroPython devices in IntelliJ IDEA and PyCharm.
- intellij-micropython - Plugin for MicroPython devices in IntelliJ and PyCharm.
The two of these are the same project, but one link is to the Github (which links back to the JetBrains plugin page) - and the other link is to the JetBrains plugin page (which links back to the Github)
=> Remove Duplicate Entry

readme.md
On merge I realized some bad typos / spelling in the PR https://github.com/mcauser/awesome-micropython/pull/18.
This PR remedies this and improves the spelling.
=> Micropython EISCP: fix typo

readme.md
Feel free to skip any of the additions if you think they are too niche or insufficiently awesome :)
A few points:
1. I deleted [Micropython-scheduler](https://github.com/danicampora/Micropython-scheduler). This is a copy of my code (attribution in source). It is seven years out of date and was superseded by uasyncio V2. I no longer use it, and I wouldn't recommend it to anyone else.
2. I deleted my Embedded Artists ePaper driver as the hardware is obsolete and unobtainable.
3. The document has two places for GUI's: `lbraries/user interface` and `libraries/Display/GUI`. I suggest merging them - my personal preference is for the latter but I can see arguments both ways. I moved the micro-gui entry to the former as it seems daft to have nano-gui and micro-gui in different places.
Thanks for …
=> Contribution from Peter Hinch.

readme.md
I've just finished working version of [pico-ir](https://github.com/bartoszadamczyk/pico-ir) - IR library for Raspberry Pico
=> Add pico-ir - IR library for Raspberry Pico

readme.md
This issue resolved #38 by providing a modbus lib with client (slave) and host (master) mode.
Additionally a winbond flash library and another WiFi Manager library with encrypted password support is added
Removed all whitespaces in the [readme.md](https://github.com/mcauser/awesome-micropython/readme.md)
=> Add micropython winbond, wifimanager and modbus libs

readme.md
Searched extensively for this book, it shows up in a couple of places, but seems out-of-print / unavailable at retail (and the included Amazon link is 404)
=> Removed MicroPython for Everyone book - unlisted at retail

readme.md
Addresses #58 to clarify that PCF8591 is an ADC/DAC driver.
=> Move PCF8591 from IO expander to ADC section

readme.md
Additional temperature / pressure sensors. Note that the BMP180 has other candidates already in the list, but there were already multiple so I added this one also. BMP390 is new.
=> Add BMP390+BMP180 drivers from octaprog7

readme.md
Hey @mcauser 
I've noticed a broken link in the list. I've looked for the best possible replacement. I hope this works for you:
http://docs.micropython.org/en/latest/library/network.WIZNET5K.html?highlight=wiznet5k#class-wiznet5k-control-wiznet5x00-ethernet-modules
Cheers,
Peter
=> Updating broken link

readme.md
- `micropython-package-template`in `Code Generation` section
- Removed trailing whitespace at `micropython-aioschedule` to comply with [contributing](./contributing.md) guideline
=> Add micropython-package-template to Code generation section

readme.md
NB re-sending PR since I lost some work locally - accounting for comments on #81, left Contributing where it was and reverted a mistaken URL change
Companion / follow-up to #80 
- updated links for redirects and 404s (some drivers moved to `micropython-lib`, other third party repos moved around)
- removed link to Slack, project uses Discord
- added link to Mastodon account (although it is new / not yet active)
- fixed a couple of `awesome-lint` issues (remaining are a couple of double-link situations and a header, but this is already in the main Awesome List of Lists, so minor)
=> Fix urls (replaces #81)

readme.md
Add `micropython-i2c-lcd` library to README in `LCD Character` section
Available for installation via [PyPI](https://pypi.org/project/micropython-i2c-lcd/), documented at [RTD](https://micropython-i2c-lcd.readthedocs.io/en/latest/) and test released on every PR via [Test PyPI](https://test.pypi.org/project/micropython-i2c-lcd/)
=> Add micropython-i2c-lcd lib for HD44780 I2C LCDs with 16x2 and 20x4

readme.md
I want to suggest [micropython-stepper](https://github.com/redoxcode/micropython-stepper) as an addition for this list.
I think the library offers a good documentation and is available for download on pypi and therefore within thonny.
There are some other stepper related libraries in this list, but i think there is none that offers the same functionality. Also a lot of those lack documentation.
=> suggesting to add micropython-stepper

readme.md
I want to suggest [micropython-servo](https://github.com/redoxcode/micropython-servo) as an addition for this list.
I think the library offers a good documentation and is available for download on pypi and therefore within thonny.
There is no comparable library in the list yet.
=> suggesting micropython-servo for addition

readme.md
I want to suggest [micropython-ppm_reader](https://github.com/redoxcode/micropython-ppm_reader) as an addition for this list.
I think the library offers a good documentation and is available for download on pypi and therefore within thonny.
There is no comparable library in the list yet.
=> Suggesting micropython-ppm_reader for addition

readme.md
I want to suggest [micropython-dfplayer](https://github.com/redoxcode/micropython-dfplayer) for addition to this list.
There is already a library for the [DFPlayer mini](https://www.dfrobot.com/product-1121.html) with the same name in this list. 
But I think the suggested library offers a better documentation. Also if you search for micropython-dfplayer on pypi or within thonny this is the one that will show up.
I don't want to suggest the existing library to be excluded, but rather this other version to be included as well.
Let me know what you think.
=> Suggesting micropython-dfplayer for addition.

readme.md
Add `micropython-eeprom` library to README in `EEPROM` section
Available for installation via [PyPI](https://pypi.org/project/micropython-eeprom/), documented at [RTD](https://micropython-eeprom.readthedocs.io/en/latest/) and test released on every PR via [Test PyPI](https://test.pypi.org/project/micropython-eeprom/)
=> Add micropython-eeprom package for AT24Cxx EEPROM

readme.md
Add `micropython-ds1307` library to README in `RTC` section
Available for installation via [PyPI](https://pypi.org/project/micropython-ds1307/), documented at [RTD](https://micropython-ds1307.readthedocs.io/en/latest/) and test released on every PR via [Test PyPI](https://test.pypi.org/project/micropython-ds1307/)
=> Add micropython-ds1307 package for DS1307 RTC

readme.md
Adds framebuf2: a MicroPython FrameBuffer extension: larger and rotated font, triangles and circles
=> suggested addition: FrameBuffer extension

readme.md
Not sure where this library has gone, and the link is dead, so probably best to remove to avoid confusion.
=> Remove quickled library (broken link; closes #113)

.github/workflows/allow-list.txt, .github/workflows/check-links.yml, readme.md
Had to remove the [micropython_quickled](https://github.com/thebaron88/micropython_quickled) entry as well, as the repo has been deleted and couldn't find an alternative link for the same project.
Added a couple of entries into an "allow list", kickstarter blocks with non-browser user agents, and the ST link also times out for some reason (the URL works works fine on my laptop with curl 🤷 ).
Some of the `awesome_bot` command line flags have been added over time in my awesome list to avoid getting false positives, like the 429 error which is usually thrown when there are a lot of link on the same domain (like github.com), or allowing redirects, as you'd be surprised how often websites move their links around.
=> Set up CI to check links daily, on commits, and PRs

readme.md
- Add micropython-stubs 
- update micropython-stubber description
- add Micropython-magic 
for `micropython-magic` I added an additional category ## Jupyter as im pretty sure there are a few other ipython/jupyter integrations out there that might be added at some time.
=> add micropython-stubs

readme.md
Added mcp230xx library with interrupt handling.
This is a fork from https://github.com/ShrimpingIt/micropython-mcp230xx which I have extended.
=> Added mcp230xx library with interrupt handling

readme.md
Add an accelerometer and pressure sensor driver. 
Both were listed in this MicroPython discussion: [Implementing an IMU/accelerometer/gyro driver? Use the FIFO!](https://github.com/orgs/micropython/discussions/15512)
I've marked both drivers with "⏩" to indicate that the driver supports FIFO access. That was [suggested in that discussion](https://github.com/orgs/micropython/discussions/15512#discussioncomment-10106077) by @Josverl and I think it's a good idea to try out. Would be good to review other drivers and add the same badge where appropriate.
=> Add BMP3xx and BMA423 drivers

readme.md
About a week or two ago I needed a Perlin library for Micropython, but couldn't find any, so I made one!
It's mostly written in C for performance reasons. Though I do plan to still add a vanilla Micropython version, though that will have a notable speed decrease, but will be more compatible / readable.
Greetings!
~Sjaak
P.s. Some sections aren't sorted alphabetically (for example Mathematics), so I've added myself at the bottom of the list.
=> Add Micropython Perlin library

readme.md
I have just released the first version of my camera-API. I based myself in the API from circuitpython, which is very good IMHO. At the moment I can compile all generic esp32 boards with my driver, and I think, if the repo is more easy to find, more will follow.
=> Add Micropython-camera-API to Camera section in readme.md

readme.md
I recently needed to read/create some .zip files. So I ported the CPython zipfile module to MicroPython.
=> Add micropython-zipfile

readme.md
thanks for all your great work on this!
=> added micropython-MCP3001 ADC

readme.md
Merged two sections with the same types of sensors. Put air pressure in the name for those who search for the word pressure.  I added (archived) to the repos that were archived by the original author. 
This issue was brought up in: "two headings with same sensors - Barometer & Pressure #173"
=> merged Barometer and Air Pressure, noted archived repos
