mcauser/awesome-micropython

readme.md
Several developer tools that are handy
=> Developer Workflow Tools

readme.md
* Added Jetbrains plugin
* Added Thonny IDE
* Added uMath
* Added Book by Charles Bell
* Added Analytics section
* Alphabetized Developer Workflow list
=> Several Additions to Awesome Micropython

readme.md
Added tve/mqboard to MQTT
Re-Ordered MQTT section to be more alphabetical(ish)
=> MQTT Library

readme.md
=> Add micropython-nano-gui

readme.md
Recently, released, adding the eiscp library.
=> Add eiscp micropython library

readme.md
I added it to the "Shells - On Host" section. Out of every category I think that one fits the best.
=> Added mpsync to readme.md

readme.md
Add the micropython-mdns library which supports MDNS with Service Discovery support.
=> Add micropython-mdns library

readme.md
=> Added "ESP32 ADC driver using reference voltage calibration value from efuse."

readme.md
Hi Mike,
i have added my personal library, see if they can be of interest to you.
=> Added some libs: uble, ucrypto and ucryptoauthlib

readme.md
Suggestion to add BIPES project (https://bipes.net.br/) to awesome-micropython. BIPES includes MQTT, IDE, Web Serial Console, dashboard, code generation, etc. It works as a free service at http://bipes.net.br/beta2/ui/ and is also an open software: https://github.com/BIPES.
Hope you like/fits awesome-micropython!
best regards!
Rafael
=> Suggestion to add BIPES project

readme.md
a simple driver for these little low-voltage displays
=> added LCM1602-14_LCD_Library 3.3 V character display driver

readme.md
This brilliant tool really needs more promotion!
=> Reference mpremote

readme.md
Ethernet driver, example python code and YouTube.
=> Add RP2040 Ethernet example

contributing.md
Just a one word typo fix, thanks!
=> Fix typo in word sentence

readme.md
- Update any http:// URLs to https://
=> updates for https linkage

readme.md
- Add Codeberg to Libraries section
=> add codeberg

readme.md
Add `micropython-nextion` library to README, see https://pypi.org/project/micropython-nextion/
=> add micropython-nextion lib

readme.md
Added new 2022 Apress/Springer book
Changed links for Apress -> Springer
Changed Amazon link -> McGraw Hill AU (most others link to publisher sites)
=> Added new book, updated publisher links

readme.md
Added a hyphen separator to mpremote entry
Added a word to improve wording of entry
=> Trivial: Add hyphen separator and improve content

readme.md
I've been using Matt Trentini's DotStar library - it is great.
=> LEDs: Added Matt's DotStar library

readme.md
- Add CoderDojo Twin Cities MicroPython for Kids resources
=> Add CoderDojo coding curriculum

readme.md
See [MicroPython discussion 9150](https://github.com/orgs/micropython/discussions/9150).
=> Add a link to octaprog7's SHT85 temp and humidity sensor driver

readme.md
I've written meerkat - a framework to collect JSON formatted data from I2C sensors using either MicroPython or Raspberry Pi.
=> Add meerkat - I2C Data Acquisition Framework

readme.md
Library works well with the LIS3DH in the samd-based Seeed Studio [Wio Terminal](https://www.seeedstudio.com/wio-terminal)
=> Added LIS3DH 3-axis accelerometer

readme.md
Books seem to be popping up recently, this one is Pico W specific.
=> Added new Pico W book (fall 2022, independently published)

readme.md
=> Update ucrypto description

readme.md
Adding mpbridge tool mentioned in the GH Discussions
=> Shells: add mpbridge utility

readme.md
This is not a single addition of a new item; this is a lot of changes throughout the list...
- consistency: align usage, capitalisation of terminology throughout e.g. WiFi, MicroPython, ESP32, MHz/GHz, sensor names etc etc. Aiming to use the official / brand-specified / defined spellings and capitalisations throughout
- awesome-linter: ensure each item has a hyphen between title and description
- fix some typos
Also...
- rewrote the piece about library management (mip is coming / latest docs refer to that)
- updated the community links to point to GH Discussions, move Discord up, mark previous forums as archived etc.
Future
- I plan to recheck the links for current status
- there are a few remaining awesome-linter issues that could optionally be looked into.
=> Chore: linting, spelling, consistency fixes.

readme.md
New UI / IDE tool specifically for Espressif boards.
=> Add ESP32-MPY-Jama UI / IDE tool

readme.md
Adding I2S driver as suggested by @robert-hh
=> Added SGTL5000 driver (closes #88)

readme.md
TSic sensors are highly accurate (±0.1 °C) but digital communications require precise pulse timing.
=> Add micropython-zacwire

readme.md
This is an online book/documentation but also strongly related to the nearby links. Where would you put it?
=> link to micropython-usermod

readme.md
Hi Mike, a pr for add my library for cryptography
=> Add ucryptography library

readme.md
should be fairly straightforward 👍🏻
=> Add Brian Pugh's Tamp library

readme.md
=> Suggested addition: SH1107 display driver

readme.md
these good value for money speaking boards work well
=> added SYN6988 text to speech module

readme.md
=> Add mpremote extension for VSCode

readme.md
Hi and thank you for this great resource. It is very valuable when learning about the different modules/libraries for MicroPython.
Proposing to add another library to AI section, https://github.com/emlearn/emlearn-micropython
Disclaimer: I am the author of the library.
=> readme.md: Add emlearn-micropython to AI section

readme.md
[`micropg_lite`](https://github.com/TimonW-Dev/micropg_lite) was [announced by the author](https://discord.com/channels/574275045187125269/1012726713291128862/1151597391418507394) on the MicroPython discord.
=> Add micropg_lite

readme.md
Hi,
I added an librarie to receive and decode the dcf77 time telegram.
=> Added dcf77 receiver and decoder

readme.md
Adds a reference to this as a stand-alone module, also to its use with the Schedule module.
=> Astronomy: Sun and Moon rise/set calculation

readme.md
added Micropython driver for Panasonic SN-GCJA5 particulate matter (PM) sensor.
=> Update readme.md for SN-GCJA5

readme.md
micropython Far Too Simple Config File
a simplicistic way of storing configuration data for projects written in micropython. (single file, 92 lines of code)
=> Update readme.md added uPyftsConf

readme.md
Also uasyncio->asyncio in my tutorial.
=> Add micropython-touch GUI

readme.md
#150 
Add `max31865` library to README in the Temperature Analog Section.
=> Update readme.md to add MAX31865

readme.md
=> Add new book by Simon Monk.

readme.md
Hi @mcauser. Here is a suggestion for a new library :)
Technically, this is a file/data format. But I could not find a very good category for that, so I put it under "mathematics" -  that is where the rest of the numpy-related stuff. I think people will find it there :) But please do let me know if you want me to move it elsewhere.
=> Add micropython-npyfile - Numpy .npy file support library

readme.md
=> Add ViperIDE

readme.md
https://github.com/vshymanskyy/wasm2mpy
=> Add wasm2mpy

readme.md
https://github.com/vshymanskyy/aiodns
=> Add aiodns

readme.md
Adds a library that I have been working on - MicroPython driver for CrateDB.
=> Adds MicroPython driver for CrateDB

readme.md
added multi-sensor driver for Bosch BMP585, BMP581, BMP390, and BMP280 sensors
=> Update readme.md with new BMPxxx driver - BMP585, BMP581, BMP390, BMP280

readme.md
Hello everyone,
Due to the new micorpg_lite version I thought it would make sense to update the description.
Best regards
Timon
=> Changed the description of micropg_lite

readme.md
This is intended to propose the enigmapython project
=> readme.md update with enigmapython reference

readme.md
=> Add mpflash.
